name: kikoba_smart
description: A smart app for Tanzanian rotating savings groups (vikoba)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.1
  url_launcher: ^6.2.5


  # Firebase
  firebase_auth: ^6.0.0

  # State management
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # Routing
  go_router: ^16.0.0

  # Utilities
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.6
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


