// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAzJ5O85hm5b0R4C74Ss2-ZhMmVNCaxA',
    appId: '1:393700849029:web:4f88bc9f4b69c05420c0ec',
    messagingSenderId: '393700849029',
    projectId: 'kikoba-smart',
    authDomain: 'kikoba-smart.firebaseapp.com',
    storageBucket: 'kikoba-smart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzr9q7X7sNUbqoT8n3x-QvRPXeqq77F-s',
    appId: '1:393700849029:android:0a99772f65525b5420c0ec',
    messagingSenderId: '393700849029',
    projectId: 'kikoba-smart',
    storageBucket: 'kikoba-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuq0Ebg2z1Y2EDF-VpeAcuZ36woXh4E-M',
    appId: '1:393700849029:ios:3078f41830f85a8c20c0ec',
    messagingSenderId: '393700849029',
    projectId: 'kikoba-smart',
    storageBucket: 'kikoba-smart.firebasestorage.app',
    iosBundleId: 'com.example.kikobaSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuq0Ebg2z1Y2EDF-VpeAcuZ36woXh4E-M',
    appId: '1:393700849029:ios:3078f41830f85a8c20c0ec',
    messagingSenderId: '393700849029',
    projectId: 'kikoba-smart',
    storageBucket: 'kikoba-smart.firebasestorage.app',
    iosBundleId: 'com.example.kikobaSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsAzJ5O85hm5b0R4C74Ss2-ZhMmVNCaxA',
    appId: '1:393700849029:web:900761200eb7db0120c0ec',
    messagingSenderId: '393700849029',
    projectId: 'kikoba-smart',
    authDomain: 'kikoba-smart.firebaseapp.com',
    storageBucket: 'kikoba-smart.firebasestorage.app',
  );

}